# Generated by Django 2.1.3 on 2018-11-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('Airline', models.CharField(max_length=30)),
                ('AirPlane_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Num_of_seat', models.IntegerField()),
                ('Made_by_Company', models.CharField(max_length=100)),
                ('Maintenance_Day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('Ap_Code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Terminal', models.CharField(max_length=100)),
                ('Gate', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Airplain_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_info.AirPlane')),
            ],
        ),
        migrations.CreateModel(
            name='Flight_captain',
            fields=[
                ('First_name', models.CharField(max_length=100)),
                ('Second_name', models.CharField(max_length=100)),
                ('Birthday', models.DateField()),
                ('home_address', models.CharField(max_length=100)),
                ('ssn', models.IntegerField()),
                ('C_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='From_to',
            fields=[
                ('F_T_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Departure_loc', models.CharField(max_length=100)),
                ('Arrival_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time_line',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Departure_time', models.DateField()),
                ('Arrival_time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='FTID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_info.From_to'),
        ),
        migrations.AddField(
            model_name='airport',
            name='TID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_info.Time_line'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='Captain_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_info.Flight_captain'),
        ),
    ]
